### ISSUE TITLE
How to show in Unity 

### ISSUE THREAD

**Issue by JackWei0310** [nanoxas/sketch-to-terrain#1]
Thanks for sharing your code! I tried to follow you step and I completed the training part. But I do not know how you connect model with unity. Can you give me some advices so that I can see the training results?

**Comment by nanoxas** [comment]
Hi, first of all, I recommend seeing the results using python first before going into unity.
Use the functions I programmed or you can make your own function to sample the generator.
to test the model with a sketch you can save all the required parts as an image and then build a matrix concatenating the ridges, rivers, peaks and basins in the third dimension of the image.
Use matplotlib to plot the results.

If it works fine, then you have to save the model and convert it into a protobuf file (tensorflow). With that you can convert it into barracuda (Unity neural network kit) and use it as you please.

I had a lot of work recently so I couldn't finish properly this last part, thats why I havent published it yet.

**Comment by JackWei0310** [comment]
Thanks. I will try to follow your suggestions! :-)
