### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by suoarski** [nanoxas/sketch-to-terrain#5]
Was just wondering what the licensing terms are for this project.

I'm considering to use parts of this code in a project I have regarding erosion simulations. Since I'm still fairly new to tensorflow, I was thinking of repurposing parts of this project. I don't see a license attached to this repository, so I thought I'd ask before I continue to do so.

If you're ok with that, I'll make sure to fully cite this github and the corresponding paper wherever it is appropriate for me to do so.

Thanks in advance, this is a really amazing project!

**Comment by nanoxas** [comment]
Yes, I forgot to upload the file. You can check it now.

**Comment by suoarski** [comment]
Great, thank you for uploading the license!
